[project]
name = "agentserver"
version = "0.1.0"
description = "Autism assessment analysis server"
requires-python = ">=3.8"
dependencies = [
    "fastapi>=0.104.1",
    "uvicorn>=0.24.0",
    "pydantic>=2.5.0",
    "requests>=2.31.0",
]